/** 32 departamentos de Colombia + Bogotá D.C. */
export const DEPARTAMENTOS = [
  'Amazonas',
  'Antioquia',
  'Arauca',
  'Atlántico',
  'Bogotá D.C.',
  'Bolívar',
  'Boyacá',
  'Caldas',
  'Caquetá',
  'Casanare',
  'Cauca',
  'Cesar',
  'Chocó',
  'Córdoba',
  'Cundinamarca',
  'Guainía',
  'Guaviare',
  'Huila',
  'La Guajira',
  'Magdalena',
  'Meta',
  'Nariño',
  'Norte de Santander',
  'Putumayo',
  'Quindío',
  'Risaralda',
  'San Andrés y Providencia',
  'Santander',
  'Sucre',
  'Tolima',
  'Valle del Cauca',
  'Vaupés',
  'Vichada',
]

/** Capitales por departamento (útil para autocompletar ciudad) */
export const CAPITALES = {
  'Amazonas':                   'Leticia',
  'Antioquia':                  'Medellín',
  'Arauca':                     'Arauca',
  'Atlántico':                  'Barranquilla',
  'Bogotá D.C.':                'Bogotá',
  'Bolívar':                    'Cartagena',
  'Boyacá':                     'Tunja',
  'Caldas':                     'Manizales',
  'Caquetá':                    'Florencia',
  'Casanare':                   'Yopal',
  'Cauca':                      'Popayán',
  'Cesar':                      'Valledupar',
  'Chocó':                      'Quibdó',
  'Córdoba':                    'Montería',
  'Cundinamarca':                'Bogotá',
  'Guainía':                    'Inírida',
  'Guaviare':                   'San José del Guaviare',
  'Huila':                      'Neiva',
  'La Guajira':                 'Riohacha',
  'Magdalena':                  'Santa Marta',
  'Meta':                       'Villavicencio',
  'Nariño':                     'Pasto',
  'Norte de Santander':         'Cúcuta',
  'Putumayo':                   'Mocoa',
  'Quindío':                    'Armenia',
  'Risaralda':                  'Pereira',
  'San Andrés y Providencia':   'San Andrés',
  'Santander':                  'Bucaramanga',
  'Sucre':                      'Sincelejo',
  'Tolima':                     'Ibagué',
  'Valle del Cauca':            'Cali',
  'Vaupés':                     'Mitú',
  'Vichada':                    'Puerto Carreño',
}
