// 60 ítems de la Resolución 0312 de 2019 — empresas > 50 trabajadores
export const ITEMS_0312 = [
  { num:1,  codigo:"1.1.1",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Responsable del SG-SST (4%)",                              item:"Responsable del Sistema de Gestión de Seguridad y Salud en el Trabajo SG-SST", criterio:"Asignar una persona con el perfil exigido para diseñar e implementar el SG-SST: profesional en SST o profesional con posgrado en SST, con licencia vigente.", evidencia:"Acto de designación; hoja de vida; soportes académicos; licencia SST; certificado curso 50 h.", aplicabilidad:"General", peso:0.5, refLegal:"Art. 16 / Art. 27" },
  { num:2,  codigo:"1.1.2",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Responsable del SG-SST (4%)",                              item:"Responsabilidades en el Sistema de Gestión de SST", criterio:"Asignar y documentar responsabilidades específicas en SST a todos los niveles de la organización para el desarrollo y mejora continua del sistema.", evidencia:"Manual de funciones; matriz de responsabilidades; comunicaciones internas; organigrama.", aplicabilidad:"General", peso:0.5, refLegal:"Art. 16 / Art. 27" },
  { num:3,  codigo:"1.1.3",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Responsable del SG-SST (4%)",                              item:"Asignación de recursos para el Sistema de Gestión de SST", criterio:"Definir y asignar el talento humano y los recursos financieros, técnicos y tecnológicos requeridos para la implementación, mantenimiento y continuidad del SG-SST.", evidencia:"Presupuesto; plan anual; actas de aprobación; contratos; inventario de recursos.", aplicabilidad:"General", peso:0.5, refLegal:"Art. 16 / Art. 27" },
  { num:4,  codigo:"1.1.4",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Responsable del SG-SST (4%)",                              item:"Afiliación al Sistema de Seguridad Social Integral", criterio:"Garantizar que todos los trabajadores estén afiliados a salud, pensión y riesgos laborales.", evidencia:"Planillas PILA; certificados de afiliación; base de personal; contratos.", aplicabilidad:"General", peso:0.5, refLegal:"Art. 16 / Art. 27" },
  { num:5,  codigo:"1.1.5",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Responsable del SG-SST (4%)",                              item:"Identificación de trabajadores de alto riesgo y cotización de pensión especial", criterio:"Cuando aplique, identificar trabajadores de alto riesgo y efectuar la cotización especial a pensión.", evidencia:"Listado de cargos de alto riesgo; análisis de cargos; soportes de cotización; PILA.", aplicabilidad:"Condicional: solo si existen actividades de alto riesgo", peso:0.5, refLegal:"Art. 16 / Art. 27" },
  { num:6,  codigo:"1.1.6",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Responsable del SG-SST (4%)",                              item:"Conformación y funcionamiento del COPASST", criterio:"Conformar y garantizar el funcionamiento del Comité Paritario de Seguridad y Salud en el Trabajo - COPASST.", evidencia:"Acta de conformación; resoluciones; convocatoria; actas de reunión; plan de trabajo COPASST.", aplicabilidad:"General", peso:0.5, refLegal:"Art. 16 / Art. 27" },
  { num:7,  codigo:"1.1.7",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Responsable del SG-SST (4%)",                              item:"Capacitación de los integrantes del COPASST", criterio:"Capacitar a los integrantes del COPASST para el cumplimiento efectivo de sus responsabilidades.", evidencia:"Programa y registros de capacitación; certificados; listas de asistencia.", aplicabilidad:"General", peso:0.5, refLegal:"Art. 16 / Art. 27" },
  { num:8,  codigo:"1.1.8",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Responsable del SG-SST (4%)",                              item:"Conformación y funcionamiento del Comité de Convivencia Laboral", criterio:"Conformar y garantizar el funcionamiento del Comité de Convivencia Laboral.", evidencia:"Acta de conformación; reglamento; actas trimestrales; evidencias de gestión.", aplicabilidad:"General", peso:0.5, refLegal:"Art. 16 / Art. 27" },
  { num:9,  codigo:"1.2.1",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Capacitación en SST (6%)",                                  item:"Programa de capacitación anual", criterio:"Elaborar y ejecutar el programa anual de capacitación en promoción y prevención, incluyendo peligros prioritarios y medidas de prevención.", evidencia:"Programa anual; cronograma; contenidos; registros y evidencias de ejecución.", aplicabilidad:"General", peso:2, refLegal:"Art. 16 / Art. 27" },
  { num:10, codigo:"1.2.2",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Capacitación en SST (6%)",                                  item:"Inducción y reinducción en SST", criterio:"Realizar inducción y reinducción previas al inicio de labores, en aspectos generales y específicos del cargo.", evidencia:"Formatos de inducción y reinducción; listas de asistencia; evaluaciones.", aplicabilidad:"General", peso:2, refLegal:"Art. 16 / Art. 27" },
  { num:11, codigo:"1.2.3",  phva:"Planear", estandar:"Recursos (10%)",                      subestandar:"Capacitación en SST (6%)",                                  item:"Responsable del SG-SST con curso virtual de 50 horas", criterio:"El responsable del SG-SST debe realizar el curso virtual de 50 horas definido por MinTrabajo.", evidencia:"Certificado vigente del curso virtual de 50 horas.", aplicabilidad:"General", peso:2, refLegal:"Art. 16 / Art. 27" },
  { num:12, codigo:"2.1.1",  phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Política de SST (1%)",                                      item:"Política del SG-SST firmada, fechada y comunicada al COPASST", criterio:"Establecer por escrito la política de SST, firmada por el representante legal y revisada mínimo una vez al año.", evidencia:"Política firmada; evidencia de divulgación; control de versiones; comunicaciones al COPASST.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:13, codigo:"2.2.1",  phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Objetivos del SG-SST (1%)",                                 item:"Objetivos definidos, claros, medibles y con metas", criterio:"Definir objetivos del SG-SST coherentes con la política, claros, medibles, documentados y revisados mínimo una vez al año.", evidencia:"Documento de objetivos; indicadores; acta de revisión; comunicación a trabajadores.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:14, codigo:"2.3.1",  phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Evaluación inicial (1%)",                                   item:"Evaluación e identificación de prioridades", criterio:"Realizar la evaluación inicial del SG-SST e identificar prioridades para el plan anual.", evidencia:"Diagnóstico inicial; matriz legal; matriz de peligros; informe de brechas.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:15, codigo:"2.4.1",  phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Plan anual de trabajo (2%)",                                item:"Plan anual con objetivos, metas, responsabilidades, recursos y cronograma", criterio:"Diseñar y definir un plan anual de trabajo para el SG-SST que identifique objetivos, metas, responsabilidades y recursos.", evidencia:"Plan anual firmado; cronograma; presupuesto; seguimiento mensual.", aplicabilidad:"General", peso:2, refLegal:"Art. 16 / Art. 27" },
  { num:16, codigo:"2.5.1",  phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Conservación de la documentación (2%)",                     item:"Archivo o retención documental del SG-SST", criterio:"Contar con un sistema de archivo y retención documental para los registros que soportan el SG-SST.", evidencia:"Tabla de retención; procedimiento documental; archivo físico o digital; trazabilidad.", aplicabilidad:"General", peso:2, refLegal:"Art. 16 / Art. 27" },
  { num:17, codigo:"2.6.1",  phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Rendición de cuentas (1%)",                                 item:"Rendición sobre el desempeño", criterio:"Realizar anualmente la rendición de cuentas del desarrollo del SG-SST incluyendo a todos los niveles.", evidencia:"Informe anual; presentación; actas; evidencia de socialización.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:18, codigo:"2.7.1",  phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Normatividad aplicable (2%)",                               item:"Matriz legal", criterio:"Definir y mantener actualizada la matriz legal del Sistema General de Riesgos Laborales aplicable a la empresa.", evidencia:"Matriz legal vigente; seguimiento de cambios normativos; evaluación de cumplimiento.", aplicabilidad:"General", peso:2, refLegal:"Art. 16 / Art. 27" },
  { num:19, codigo:"2.8.1",  phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Comunicación (1%)",                                         item:"Mecanismos de comunicación y autorreporte", criterio:"Disponer de mecanismos eficaces para comunicaciones internas y externas sobre SST y autorreporte.", evidencia:"Procedimiento de comunicaciones; buzones; formatos de autorreporte; registros.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:20, codigo:"2.9.1",  phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Adquisiciones (1%)",                                        item:"Identificación y evaluación para adquisición de bienes y servicios", criterio:"Establecer un procedimiento para identificar y evaluar las especificaciones de SST en compras.", evidencia:"Procedimiento de compras; fichas técnicas; criterios SST; registros de evaluación.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:21, codigo:"2.10.1", phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Contratación (2%)",                                         item:"Evaluación y selección de proveedores y contratistas", criterio:"Establecer los aspectos de SST a considerar en la evaluación y selección de proveedores y contratistas.", evidencia:"Formato de evaluación; cláusulas contractuales; homologación; seguimiento.", aplicabilidad:"General", peso:2, refLegal:"Art. 16 / Art. 27" },
  { num:22, codigo:"2.11.1", phva:"Planear", estandar:"Gestión integral del SG-SST (15%)",  subestandar:"Gestión del cambio (1%)",                                   item:"Evaluación del impacto de cambios internos y externos", criterio:"Disponer de un procedimiento para evaluar el impacto en SST de cualquier cambio interno o externo.", evidencia:"Procedimiento de gestión del cambio; matrices de impacto; registros.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:23, codigo:"3.1.1",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Condiciones de salud en el trabajo (9%)",                   item:"Descripción sociodemográfica y diagnóstico de condiciones de salud", criterio:"Recolectar información sociodemográfica actualizada y diagnóstico de condiciones de salud del último año.", evidencia:"Base sociodemográfica; perfil epidemiológico; informe de condiciones de salud.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:24, codigo:"3.1.2",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Condiciones de salud en el trabajo (9%)",                   item:"Actividades de promoción y prevención en salud", criterio:"Desarrollar actividades de medicina del trabajo, prevención y promoción y programas de vigilancia epidemiológica.", evidencia:"PVE; cronograma de PyP; informes de ejecución; campañas; registros.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:25, codigo:"3.1.3",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Condiciones de salud en el trabajo (9%)",                   item:"Información al médico de los perfiles de cargo", criterio:"Informar al médico que realiza evaluaciones ocupacionales los perfiles de cargo con descripción de tareas.", evidencia:"Perfiles de cargo; comunicación al proveedor de medicina laboral; contratos.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:26, codigo:"3.1.4",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Condiciones de salud en el trabajo (9%)",                   item:"Evaluaciones médicas ocupacionales", criterio:"Realizar evaluaciones médicas ocupacionales conforme a la normatividad y riesgos del trabajador.", evidencia:"Profesiograma; aptitudes; certificados; citaciones; constancias de comunicación.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:27, codigo:"3.1.5",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Condiciones de salud en el trabajo (9%)",                   item:"Custodia de historias clínicas", criterio:"Tener la custodia de las historias clínicas a cargo de una IPS en SST o del médico que practica las evaluaciones.", evidencia:"Contrato con IPS o médico; procedimiento de custodia y reserva.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:28, codigo:"3.1.6",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Condiciones de salud en el trabajo (9%)",                   item:"Restricciones y recomendaciones médico laborales", criterio:"Cumplir restricciones y recomendaciones médico laborales y adecuar puestos cuando se requiera.", evidencia:"Registros de reubicación; actas de adecuación; conceptos ocupacionales.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:29, codigo:"3.1.7",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Condiciones de salud en el trabajo (9%)",                   item:"Estilos de vida y entorno saludable", criterio:"Elaborar y ejecutar un programa para promover estilos de vida saludables incluyendo prevención de farmacodependencia.", evidencia:"Programa de hábitos saludables; campañas; registros de participación.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:30, codigo:"3.1.8",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Condiciones de salud en el trabajo (9%)",                   item:"Agua potable, servicios sanitarios y disposición de basuras", criterio:"Contar con suministro de agua potable, servicios sanitarios y mecanismos para disponer excretas y basuras.", evidencia:"Inspecciones locativas; contratos; registros de limpieza; evidencia fotográfica.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:31, codigo:"3.1.9",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Condiciones de salud en el trabajo (9%)",                   item:"Eliminación adecuada de residuos sólidos, líquidos o gaseosos", criterio:"Eliminar residuos sólidos, líquidos, gaseosos y peligrosos sin poner en riesgo a los trabajadores.", evidencia:"PGIR; contratos con gestores; manifiestos; procedimientos y capacitaciones.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:32, codigo:"3.2.1",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Registro, reporte e investigación (5%)",                    item:"Reporte de accidentes de trabajo y enfermedades laborales", criterio:"Reportar a ARL y EPS los accidentes de trabajo y enfermedades laborales, y a MinTrabajo los graves o mortales.", evidencia:"FURAT/FUREL; radicados; correos; acuses de recibo.", aplicabilidad:"General", peso:2, refLegal:"Art. 16 / Art. 27" },
  { num:33, codigo:"3.2.2",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Registro, reporte e investigación (5%)",                    item:"Investigación de incidentes, accidentes y enfermedades laborales", criterio:"Investigar incidentes y accidentes con participación del COPASST, determinando causas básicas e inmediatas.", evidencia:"Informes de investigación; metodología; actas COPASST; planes de acción.", aplicabilidad:"General", peso:2, refLegal:"Art. 16 / Art. 27" },
  { num:34, codigo:"3.2.3",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Registro, reporte e investigación (5%)",                    item:"Registro y análisis estadístico de accidentes y enfermedades laborales", criterio:"Llevar registro estadístico de accidentes y enfermedades, analizarlo y usar conclusiones para mejorar el SG-SST.", evidencia:"Base estadística; indicadores; informes de análisis; tendencias.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:35, codigo:"3.3.1",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Mecanismos de vigilancia (6%)",                             item:"Medición de la frecuencia de la accidentalidad", criterio:"Medir mensualmente la frecuencia de los accidentes y clasificar el origen del peligro o riesgo.", evidencia:"Indicador calculado; ficha técnica; reporte mensual.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:36, codigo:"3.3.2",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Mecanismos de vigilancia (6%)",                             item:"Medición de la severidad de la accidentalidad", criterio:"Medir mensualmente la severidad de los accidentes y clasificar el origen del peligro.", evidencia:"Indicador calculado; reporte mensual; soporte de días perdidos.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:37, codigo:"3.3.3",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Mecanismos de vigilancia (6%)",                             item:"Medición de la mortalidad por accidentes de trabajo", criterio:"Medir anualmente la mortalidad por accidentes de trabajo y clasificar el origen del peligro.", evidencia:"Indicador anual; análisis de causalidad; informe gerencial.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:38, codigo:"3.3.4",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Mecanismos de vigilancia (6%)",                             item:"Medición de la prevalencia de enfermedad laboral", criterio:"Medir anualmente la prevalencia de enfermedad laboral y clasificar el origen del peligro.", evidencia:"Indicador anual; base de casos; informe epidemiológico.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:39, codigo:"3.3.5",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Mecanismos de vigilancia (6%)",                             item:"Medición de la incidencia de enfermedad laboral", criterio:"Medir anualmente la incidencia de enfermedad laboral y clasificar el origen del peligro.", evidencia:"Indicador anual; base de casos nuevos; informe epidemiológico.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:40, codigo:"3.3.6",  phva:"Hacer",   estandar:"Gestión de la salud (20%)",           subestandar:"Mecanismos de vigilancia (6%)",                             item:"Medición del ausentismo por causa médica", criterio:"Medir mensualmente el ausentismo por incapacidad de origen laboral y común.", evidencia:"Indicador mensual; incapacidades; análisis de ausentismo.", aplicabilidad:"General", peso:1, refLegal:"Art. 16 / Art. 27" },
  { num:41, codigo:"4.1.1",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Identificación de peligros, evaluación y valoración (15%)",  item:"Metodología para la identificación de peligros, evaluación y valoración de riesgos", criterio:"Definir y aplicar una metodología para identificar peligros y evaluar riesgos de todos los procesos y actividades.", evidencia:"Matriz de peligros; metodología; instructivo; versión vigente.", aplicabilidad:"General", peso:4, refLegal:"Art. 16 / Art. 27" },
  { num:42, codigo:"4.1.2",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Identificación de peligros, evaluación y valoración (15%)",  item:"Identificación de peligros con participación de todos los niveles", criterio:"Realizar la identificación de peligros con participación de trabajadores de todos los niveles, revisada anualmente.", evidencia:"Actas de participación; matriz actualizada; evidencias de revisión.", aplicabilidad:"General", peso:4, refLegal:"Art. 16 / Art. 27" },
  { num:43, codigo:"4.1.3",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Identificación de peligros, evaluación y valoración (15%)",  item:"Identificación de sustancias carcinógenas o con toxicidad aguda", criterio:"En empresas con sustancias carcinógenas o tóxicas, priorizar su identificación y valoración de riesgos.", evidencia:"Inventario de sustancias; FDS; matriz de riesgo químico; planes de control.", aplicabilidad:"Condicional: solo si existen estas sustancias", peso:3, refLegal:"Art. 16 / Art. 27" },
  { num:44, codigo:"4.1.4",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Identificación de peligros, evaluación y valoración (15%)",  item:"Realización de mediciones ambientales, químicos, físicos y biológicos", criterio:"Realizar mediciones ambientales de los riesgos prioritarios derivados de peligros químicos, físicos y biológicos.", evidencia:"Informes de higiene industrial; monitoreos; laboratorio; planes de intervención.", aplicabilidad:"General según exposición", peso:4, refLegal:"Art. 16 / Art. 27" },
  { num:45, codigo:"4.2.1",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Medidas de prevención y control (15%)",                     item:"Implementación de medidas de prevención y control", criterio:"Ejecutar medidas de prevención y control con base en la identificación de peligros, priorizando la intervención en la fuente.", evidencia:"Plan de intervención; controles implementados; evidencias fotográficas; registros.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
  { num:46, codigo:"4.2.2",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Medidas de prevención y control (15%)",                     item:"Verificación de aplicación de medidas de prevención y control", criterio:"Verificar la aplicación por parte de los trabajadores de las medidas de prevención y control.", evidencia:"Inspecciones comportamentales; observaciones; reportes de supervisión.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
  { num:47, codigo:"4.2.3",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Medidas de prevención y control (15%)",                     item:"Elaboración de procedimientos, instructivos, fichas y protocolos", criterio:"Elaborar procedimientos, instructivos y fichas técnicas de SST cuando se requiera y entregarlos a los trabajadores.", evidencia:"Procedimientos; instructivos; fichas técnicas; soportes de entrega o socialización.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
  { num:48, codigo:"4.2.4",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Medidas de prevención y control (15%)",                     item:"Inspecciones sistemáticas a instalaciones, maquinaria o equipos", criterio:"Elaborar formatos y realizar inspecciones sistemáticas a instalaciones, maquinaria y equipos.", evidencia:"Listas de chequeo; registros de inspección; actas COPASST; hallazgos y cierres.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
  { num:49, codigo:"4.2.5",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Medidas de prevención y control (15%)",                     item:"Mantenimiento periódico de instalaciones, equipos, máquinas y herramientas", criterio:"Realizar mantenimiento periódico de instalaciones, equipos y herramientas conforme a inspecciones y reportes.", evidencia:"Plan de mantenimiento; órdenes de trabajo; hojas de vida de equipos.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
  { num:50, codigo:"4.2.6",  phva:"Hacer",   estandar:"Gestión de peligros y riesgos (30%)", subestandar:"Medidas de prevención y control (15%)",                     item:"Entrega de EPP y capacitación en uso adecuado", criterio:"Suministrar y reponer oportunamente los EPP requeridos y capacitar en su uso correcto.", evidencia:"Matrices EPP; actas de entrega; registros de reposición; capacitación.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
  { num:51, codigo:"5.1.1",  phva:"Hacer",   estandar:"Gestión de amenazas (10%)",           subestandar:"Plan de prevención, preparación y respuesta (10%)",          item:"Plan de prevención, preparación y respuesta ante emergencias", criterio:"Elaborar un plan que identifique amenazas, evalúe vulnerabilidad e incluya planos, señalización y simulacros.", evidencia:"Plan de emergencias; análisis de vulnerabilidad; planos; registros de simulacros.", aplicabilidad:"General", peso:5, refLegal:"Art. 16 / Art. 27" },
  { num:52, codigo:"5.1.2",  phva:"Hacer",   estandar:"Gestión de amenazas (10%)",           subestandar:"Plan de prevención, preparación y respuesta (10%)",          item:"Brigada de prevención, preparación y respuesta ante emergencias", criterio:"Conformar, capacitar y dotar la brigada de emergencias según necesidades y tamaño de la empresa.", evidencia:"Documento de conformación; capacitación; entrega de dotación; roles y turnos.", aplicabilidad:"General", peso:5, refLegal:"Art. 16 / Art. 27" },
  { num:53, codigo:"6.1.1",  phva:"Verificar",estandar:"Verificación del SG-SST (5%)",       subestandar:"Gestión y resultados del SG-SST (5%)",                      item:"Definición de indicadores del SG-SST", criterio:"Definir indicadores para evaluar el SG-SST y mantener disponibles los resultados de la evaluación.", evidencia:"Fichas técnicas de indicadores; tablero; informes de resultados.", aplicabilidad:"General", peso:1.25, refLegal:"Art. 16 / Art. 27" },
  { num:54, codigo:"6.1.2",  phva:"Verificar",estandar:"Verificación del SG-SST (5%)",       subestandar:"Gestión y resultados del SG-SST (5%)",                      item:"Auditoría anual", criterio:"Realizar una auditoría anual del SG-SST planificada con participación del COPASST y con alcance a todas las áreas.", evidencia:"Programa de auditoría; informe; competencia del auditor; participación COPASST.", aplicabilidad:"General", peso:1.25, refLegal:"Art. 16 / Art. 27" },
  { num:55, codigo:"6.1.3",  phva:"Verificar",estandar:"Verificación del SG-SST (5%)",       subestandar:"Gestión y resultados del SG-SST (5%)",                      item:"Revisión por la alta dirección y alcance de la auditoría", criterio:"Revisar mínimo una vez al año, por la alta dirección, el sistema y el alcance de la auditoría.", evidencia:"Acta de revisión por la dirección; presentación de resultados; verificación de alcance.", aplicabilidad:"General", peso:1.25, refLegal:"Art. 16 / Art. 27" },
  { num:56, codigo:"6.1.4",  phva:"Verificar",estandar:"Verificación del SG-SST (5%)",       subestandar:"Gestión y resultados del SG-SST (5%)",                      item:"Planificación de auditorías con el COPASST", criterio:"Revisar el SG-SST y comunicar los resultados al COPASST y al responsable del sistema.", evidencia:"Programa de auditoría; actas COPASST; comunicación de resultados.", aplicabilidad:"General", peso:1.25, refLegal:"Art. 16 / Art. 27" },
  { num:57, codigo:"7.1.1",  phva:"Actuar",  estandar:"Mejoramiento (10%)",                  subestandar:"Acciones preventivas y correctivas (10%)",                  item:"Acciones preventivas y/o correctivas", criterio:"Definir e implementar acciones preventivas y/o correctivas con base en supervisión, inspecciones e indicadores.", evidencia:"Planes de acción; seguimiento; cierre de hallazgos; evidencias de implementación.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
  { num:58, codigo:"7.1.2",  phva:"Actuar",  estandar:"Mejoramiento (10%)",                  subestandar:"Acciones preventivas y correctivas (10%)",                  item:"Acciones de mejora conforme a revisión de la alta dirección", criterio:"Tomar medidas correctivas cuando la revisión por la alta dirección evidencie medidas inadecuadas.", evidencia:"Acta de revisión; plan de mejora; cierre de acciones; evidencias de eficacia.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
  { num:59, codigo:"7.1.3",  phva:"Actuar",  estandar:"Mejoramiento (10%)",                  subestandar:"Acciones preventivas y correctivas (10%)",                  item:"Acciones de mejora con base en investigaciones de AT y EL", criterio:"Implementar acciones preventivas y/o correctivas con base en investigaciones de accidentes y enfermedades.", evidencia:"Planes derivados de investigaciones; seguimiento; verificación de efectividad.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
  { num:60, codigo:"7.1.4",  phva:"Actuar",  estandar:"Mejoramiento (10%)",                  subestandar:"Acciones preventivas y correctivas (10%)",                  item:"Plan de mejoramiento e implementación de medidas de autoridades y ARL", criterio:"Implementar medidas y acciones correctivas producto de requerimientos de autoridades y de la ARL.", evidencia:"Plan de mejoramiento; requerimientos recibidos; respuestas; evidencias de cierre.", aplicabilidad:"General", peso:2.5, refLegal:"Art. 16 / Art. 27" },
]

export const ESTANDARES = [...new Set(ITEMS_0312.map(i => i.estandar))]

export const PHVA_COLOR = {
  Planear:   '#3B82F6',
  Hacer:     '#22C55E',
  Verificar: '#F59E0B',
  Actuar:    '#EF4444',
}

export const ESTADO_INFO = {
  CUMPLE_TOTALMENTE:      { label: 'Cumple totalmente',     cls: 'text-green-700 bg-green-50 border-green-300',    pct: 1   },
  CUMPLE_PARCIALMENTE:    { label: 'Cumple parcialmente',   cls: 'text-yellow-700 bg-yellow-50 border-yellow-300', pct: 0   },
  NO_CUMPLE:              { label: 'No cumple',             cls: 'text-red-700 bg-red-50 border-red-300',          pct: 0   },
  NO_APLICA:              { label: 'No aplica',             cls: 'text-slate-500 bg-slate-100 border-slate-300',   pct: 1   },
  EN_REVISION:            { label: 'En revisión',           cls: 'text-blue-700 bg-blue-50 border-blue-300',       pct: 0   },
}

export function calcPuntaje(estado, peso) {
  const info = ESTADO_INFO[estado]
  if (!info) return 0
  return info.pct * peso
}
